<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: evilcoderr
 * Date: Mon, 17 Jun 2013 16:41:14 +0200
 */

$conf['title'] = 'evilcoderrWiki';
$conf['start'] = 'Стартовая страница';
$conf['lang'] = 'ru';
$conf['template'] = 'monobook';
$conf['license'] = 'cc-by-sa';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';

// end auto-generated content
